## H2H

In [1]:
import pandas as pd

data = pd.read_csv('18-21April.csv')

In [2]:
dirty_data = pd.read_csv('15_April.csv')
dirty_data.head(6)
del dirty_data['name_away']
del dirty_data['name_home']

dirty_data[['price_away', 'price_home']] = dirty_data[['price_home', 'price_away']]
dirty_data = dirty_data[dirty_data['bet_format'] == 'h2h']
dirty_data

,Unnamed: 0,Game_ID,away_team,bet_format,home_team,price_away,price_home,site_title
0,0,b090968946b47874203a6bfd3e7463f9,Atlanta Hawks,h2h,Cleveland Cavaliers,-130.0,110.0,FanDuel
2,2,b090968946b47874203a6bfd3e7463f9,Atlanta Hawks,h2h,Cleveland Cavaliers,-135.0,115.0,DraftKings
4,4,b090968946b47874203a6bfd3e7463f9,Atlanta Hawks,h2h,Cleveland Cavaliers,-135.0,110.0,BetMGM
6,6,b090968946b47874203a6bfd3e7463f9,Atlanta Hawks,h2h,Cleveland Cavaliers,-132.0,110.0,BetOnline.ag
8,8,b090968946b47874203a6bfd3e7463f9,Atlanta Hawks,h2h,Cleveland Cavaliers,-135.0,115.0,William Hill (US)
...,...,...,...,...,...,...,...,...
299,299,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,410.0,-556.0,WynnBET
301,301,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,400.0,-550.0,William Hill (US)
303,303,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,420.0,-500.0,Betfair
305,305,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,420.0,-560.0,FanDuel
307,307,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,400.0,-551.0,PointsBet (US)

In [3]:
data.head(6)

,Unnamed: 0,Game_ID,away_team,bet_format,home_team,point_spread_away,point_spread_home,price_away,price_home,site_title
0,0,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,0.0,0.0,-135.0,115.0,BetOnline.ag
1,1,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,spreads,Minnesota Timberwolves,-2.0,2.0,-115.0,-105.0,BetOnline.ag
2,2,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,0.0,0.0,-132.0,112.0,FanDuel
3,3,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,spreads,Minnesota Timberwolves,-2.0,2.0,-112.0,-108.0,FanDuel
4,4,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,0.0,0.0,-130.0,110.0,DraftKings
5,5,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,spreads,Minnesota Timberwolves,-2.0,2.0,-110.0,-110.0,DraftKings

In [4]:
h2h_data = data[data['bet_format']=='h2h']
del h2h_data['point_spread_away']
del h2h_data['point_spread_home']
h2h_data

,Unnamed: 0,Game_ID,away_team,bet_format,home_team,price_away,price_home,site_title
0,0,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-135.0,115.0,BetOnline.ag
2,2,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-132.0,112.0,FanDuel
4,4,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-130.0,110.0,DraftKings
6,6,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-135.0,115.0,LowVig.ag
8,8,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-145.0,120.0,BetMGM
...,...,...,...,...,...,...,...,...
304,304,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,h2h,Brooklyn Nets,140.0,-175.0,BetRivers
306,306,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,h2h,Brooklyn Nets,140.0,-175.0,TwinSpires
308,308,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,h2h,Brooklyn Nets,140.0,-175.0,SugarHouse
310,310,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,h2h,Brooklyn Nets,152.0,-161.0,Betfair
312,312,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,h2h,Brooklyn Nets,140.0,-172.0,Unibet

In [5]:
h2h = [h2h_data, dirty_data]
h2h_combined = pd.concat(h2h)
h2h_combined

,Unnamed: 0,Game_ID,away_team,bet_format,home_team,price_away,price_home,site_title
0,0,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-135.0,115.0,BetOnline.ag
2,2,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-132.0,112.0,FanDuel
4,4,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-130.0,110.0,DraftKings
6,6,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-135.0,115.0,LowVig.ag
8,8,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-145.0,120.0,BetMGM
...,...,...,...,...,...,...,...,...
299,299,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,410.0,-556.0,WynnBET
301,301,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,400.0,-550.0,William Hill (US)
303,303,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,420.0,-500.0,Betfair
305,305,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,420.0,-560.0,FanDuel
307,307,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,400.0,-551.0,PointsBet (US)

In [6]:
games = list(h2h_combined['Game_ID'].unique())
games

['2647c9e2bee2448aff8cd9f719e18227',
 'ff9b37d3b14de9f0e5319e0816416789',
 '9971e4841a520772a8ec99fc468ee7be',
 'd33175375c539f73997dc63c4382e74e',
 '3da102746320bce14827087c0e745b06',
 'f9513b80a2533875a0d938447550ed0b',
 '200f24fa228c33d3bb5bf2034f5267c5',
 'd80ec53b49c8870b7804b37cdb7891e6',
 'b090968946b47874203a6bfd3e7463f9',
 '65eb4cf3feea486bcc883e4066f9362a',
 '4d9d3ef86cfc82a4867ee33aabfc68f5',
 '417ab149da824d7edfce153c3f08c71f',
 'ea05ba0c66880594fc2fe07497889f93',
 'd3d7f848492b501db285bfd0d909b827',
 'f614fee7ff019a4579388872c8cdba69',
 '4aa919d9d10d73ab59f145c35afbf782']

In [7]:
h2h_out = dict()

h2h_out['2647c9e2bee2448aff8cd9f719e18227'] = {'winner':'away', 'home_prob': 45.5}
h2h_out['ff9b37d3b14de9f0e5319e0816416789'] = {'winner':'away', 'home_prob': 78.5}
h2h_out['9971e4841a520772a8ec99fc468ee7be'] = {'winner':'away', 'home_prob': 45.2}
h2h_out['b090968946b47874203a6bfd3e7463f9'] = {'winner':'away', 'home_prob': 45.2}
h2h_out['65eb4cf3feea486bcc883e4066f9362a'] = {'winner':'away', 'home_prob': 47.4}
h2h_out['4d9d3ef86cfc82a4867ee33aabfc68f5'] = {'winner':'away', 'home_prob': 32.5}
h2h_out['417ab149da824d7edfce153c3f08c71f'] = {'winner':'away', 'home_prob': 69.5}
h2h_out['ea05ba0c66880594fc2fe07497889f93'] = {'winner':'home', 'home_prob': 63.9}
h2h_out['d3d7f848492b501db285bfd0d909b827'] = {'winner':'home', 'home_prob': 70.2}
h2h_out['f614fee7ff019a4579388872c8cdba69'] = {'winner':'home', 'home_prob': 63.0}
h2h_out['4aa919d9d10d73ab59f145c35afbf782'] = {'winner':'home', 'home_prob': 82.5}

In [8]:
away = list(h2h_combined['away_team'].unique())
home = list(h2h_combined['home_team'].unique())

teams = list(set(away+home))

In [9]:
teams

['Memphis Grizzlies',
 'Atlanta Hawks',
 'New Orleans Pelicans',
 'Minnesota Timberwolves',
 'Chicago Bulls',
 'Cleveland Cavaliers',
 'Milwaukee Bucks',
 'Miami Heat',
 'Denver Nuggets',
 'Philadelphia 76ers',
 'Utah Jazz',
 'Boston Celtics',
 'Brooklyn Nets',
 'Golden State Warriors',
 'Dallas Mavericks',
 'Phoenix Suns',
 'Los Angeles Clippers',
 'Toronto Raptors']

In [10]:
wins_dict = dict()

wins = [46, 44, 42, 44, 52, 51, 48, 53, 46, 53, 43, 51, 64, 49, 48, 51, 36, 56]
combined = dict(zip(teams, wins))

In [11]:
h2h_combined['away_wins'] = h2h_combined['away_team'].map(combined)
h2h_combined['home_wins'] = h2h_combined['home_team'].map(combined)

In [12]:
h2h_combined

,Unnamed: 0,Game_ID,away_team,bet_format,home_team,price_away,price_home,site_title,away_wins,home_wins
0,0,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-135.0,115.0,BetOnline.ag,46,44
2,2,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-132.0,112.0,FanDuel,46,44
4,4,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-130.0,110.0,DraftKings,46,44
6,6,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-135.0,115.0,LowVig.ag,46,44
8,8,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,h2h,Minnesota Timberwolves,-145.0,120.0,BetMGM,46,44
...,...,...,...,...,...,...,...,...,...,...
299,299,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,410.0,-556.0,WynnBET,52,48
301,301,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,400.0,-550.0,William Hill (US),52,48
303,303,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,420.0,-500.0,Betfair,52,48
305,305,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,420.0,-560.0,FanDuel,52,48
307,307,4aa919d9d10d73ab59f145c35afbf782,Chicago Bulls,h2h,Milwaukee Bucks,400.0,-551.0,PointsBet (US),52,48

In [13]:
# Create a visualizations including expected value? since there is a probability for the home team to win

## Spreads

In [14]:
spread_data = data[data['bet_format'] == 'spreads']
spread_data

,Unnamed: 0,Game_ID,away_team,bet_format,home_team,point_spread_away,point_spread_home,price_away,price_home,site_title
1,1,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,spreads,Minnesota Timberwolves,-2.0,2.0,-115.0,-105.0,BetOnline.ag
3,3,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,spreads,Minnesota Timberwolves,-2.0,2.0,-112.0,-108.0,FanDuel
5,5,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,spreads,Minnesota Timberwolves,-2.0,2.0,-110.0,-110.0,DraftKings
7,7,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,spreads,Minnesota Timberwolves,-2.0,2.0,-110.0,100.0,LowVig.ag
9,9,2647c9e2bee2448aff8cd9f719e18227,Memphis Grizzlies,spreads,Minnesota Timberwolves,-2.5,2.5,-110.0,-110.0,BetMGM
...,...,...,...,...,...,...,...,...,...,...
303,303,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,spreads,Brooklyn Nets,3.5,-3.5,-109.0,-112.0,Barstool Sportsbook
305,305,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,spreads,Brooklyn Nets,3.5,-3.5,-109.0,-112.0,BetRivers
307,307,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,spreads,Brooklyn Nets,3.5,-3.5,-109.0,-112.0,TwinSpires
309,309,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,spreads,Brooklyn Nets,3.5,-3.5,-109.0,-112.0,SugarHouse
313,313,d80ec53b49c8870b7804b37cdb7891e6,Boston Celtics,spreads,Brooklyn Nets,3.5,-3.5,-109.0,-111.0,Unibet